"""RequestBot Initial revision 1

Revision ID: 8f13150d62d6
Revises: 
Create Date: 2024-10-06 12:51:33.792794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f13150d62d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='request_bot'
    )
    op.create_table('temporary_events_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tg', sa.BigInteger(), nullable=False),
    sa.Column('type_event', sa.String(length=128), nullable=False),
    sa.Column('info', sa.String(length=2048), nullable=True),
    sa.Column('phone', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='request_bot'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tg', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=320), nullable=False),
    sa.Column('fullname', sa.String(length=320), nullable=False),
    sa.Column('fio', sa.String(length=320), nullable=False),
    sa.Column('date_reg', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='request_bot'
    )
    op.create_table('created_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.TIMESTAMP(), nullable=False),
    sa.Column('type_event', sa.String(length=128), nullable=False),
    sa.Column('info', sa.String(length=2048), nullable=False),
    sa.Column('phone', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['request_bot.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='request_bot'
    )
    op.create_table('user_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id_topic_chat', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['request_bot.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='request_bot'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_chats', schema='request_bot')
    op.drop_table('created_events', schema='request_bot')
    op.drop_table('users', schema='request_bot')
    op.drop_table('temporary_events_data', schema='request_bot')
    op.drop_table('admin_group', schema='request_bot')
    # ### end Alembic commands ###
